Switch to systemd

diff --git a/debian/signing-milter.postinst b/debian/signing-milter.postinst
--- a/debian/signing-milter.postinst
+++ b/debian/signing-milter.postinst
@@ -1,47 +1,59 @@
 #!/bin/sh
+# postinst script for signing-milter
 #
-#  signing-milter - debian/postinst
-#  Copyright (C) 2010,2018  Andreas Schulze
-#
-#  This program is free software; you can redistribute it and/or modify
-#  it under the terms of the GNU General Public License as published by
-#  the Free Software Foundation; only version 2 of the License is applicable.
-#
-#  This program is distributed in the hope that it will be useful,
-#  but WITHOUT ANY WARRANTY; without even the implied warranty of
-#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#  GNU General Public License for more details.
-#
-#  You should have received a copy of the GNU General Public License along
-#  with this program; if not, write to the Free Software Foundation, Inc.,
-#  51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-#
-#  Authors:
-#    Andreas Schulze <signing-milter at andreasschulze.de>
-#
-#
+# see: dh_installdeb(1)
 
 set -e
 
-case "$1" in
-    configure)
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-        if ! getent passwd signing-milter >/dev/null; then
-            adduser --quiet --system --group --no-create-home --home /etc/signing-milter signing-milter
+
+case "$1" in
+    install)
+        echo "Setting up signing-milter group and user"
+        # Now we have to ensure the following state:
+        # /etc/passwd: mysql:x:100:101:MySQL Server:/nonexistent:/bin/false
+        # /etc/group:  mysql:x:101:
+        #
+        # Sadly there could any state be present on the system so we have to
+        # modify everything carefully i.e. not doing a chown before creating
+        # the user etc...
+        # Copied from mysql-server 5.5
+
+        # creating mysql group if he isn't already there
+        if ! getent group signing-milter >/dev/null; then
+            # Adding system group: mysql.
+            addgroup --system signing-milter >/dev/null
         fi
 
-        echo " - setzte Rechte fuer /etc/signing-milter"
+        # creating mysql user if he isn't already there
+        if ! getent passwd signing-milter >/dev/null; then
+            # Adding system user: mysql.
+            adduser \
+            --system \
+            --disabled-login \
+            --ingroup mysql \
+            --no-create-home \
+            --home /nonexistent \
+            --gecos "signing-milter" \
+            --shell /bin/false \
+            signing-milter >/dev/null
+        fi
+    ;;
+    configure)
+        echo "Setting up signing-milter folder permissions"
         chgrp --changes signing-milter /etc/signing-milter/
         chmod --changes 0750 /etc/signing-milter/
-
-        if [ ! -L /etc/service/signing-milter ]; then
-            echo " - richte signing-milter ein ( starte aber noch nicht )"
-            touch /var/lib/supervise/signing-milter/down
-            ln -s ../../var/lib/supervise/signing-milter /etc/service/
-        else
-            echo " - starte signing-milter neu"
-            svc -t /var/lib/supervise/signing-milter || :
-        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
@@ -52,6 +64,9 @@ case "$1" in
         exit 1
     ;;
 esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
